apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgprocess
spec:
  selector:
    matchLabels:
      app: imgprocess
  replicas: 1
  template:
    metadata:
      labels:
        app: imgprocess
    spec:
      containers:
        - name: imgprocess
          image: joaqwin/imgprocess:6
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "120Mi"
              cpu: "80m"
            limits:
              memory: "250Mi"
              cpu: "280m"