apiVersion: v1
kind: Service
metadata:
  name: svc-rabbit
  labels:
    app: svc-conejo
spec:
  type: ClusterIP
  selector:
    app: rabbit
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
