apiVersion: v1
kind: Service
metadata:
  name: imgprocess-service
spec:
  selector:
    app: imgprocess
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30000